---
- hosts: webservers
  sudo: yes
  tasks:
  - name: install apache
    apt: name=apache2
  - name: write web page
    template: src=templates/index.html.j2 dest=/var/www/html/index.html
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
